### ISSUE TITLE
Add result text once chances are exhausted or guessed the word

### ISSUE THREAD

**Issue by aneeshpanda** [IEEE-VIT/hangman-react#18]
**Please describe the feature you want this project to offer**
Shows a play again button.

**Describe the solution you'd like**
Add in a result text.

**Comment by ankitgauri26** [comment]
Can i work on this? Please assign it to me to get started

**Comment by aneeshpanda** [comment]
> Can i work on this? Please assign it to me to get started

@ankitgauri26 I'm assigning this issue to you!

**Comment by ankitgauri26** [comment]
@aneeshpanda - I tried to run the project but nothing is displayed. What exactly I need to build? Request you to please provide full details so that I start working on this. Thanks in advance.

**Comment by aneeshpanda** [comment]
@ankitgauri26 It's an empty project right now, to be built upon.

**Comment by ankitgauri26** [comment]
@aneeshpanda  - Thanks for your reply. According to the issue "Add result text once chances are exhausted or guessed the word", what are the chances? as this is the empty project, we need to first build other parts before working on this? If not, can you give me some details what exactly needs to be build so that i can start working?

**Comment by aneeshpanda** [comment]
@ankitgauri26 Yeah, the other parts have to be made to be before this issue is taken up. They have been already created you can take a look at them.
